apiVersion: v2
name: docs-indexer-app
appVersion: '[[ .AppVersion ]]'
description: Indexes content for the docs search engine.
annotations:
  io.giantswarm.application.team: honeybadger
version: '[[.Version]]'
home: https://github.com/giantswarm/docs-indexer
