apiVersion: v2
name: docs-indexer-app
version: 4.1.0-dev
appVersion: 4.1.0-dev
description: Indexes content for the docs search engine.
home: https://github.com/giantswarm/docs-indexer
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
annotations:
  application.giantswarm.io/team: honeybadger
  io.giantswarm.application.team: honeybadger
