apiVersion: v2
name: docs-indexer-app
appVersion: '4.1.1'
description: Indexes content for the docs search engine.
annotations:
  io.giantswarm.application.audience: giantswarm
  io.giantswarm.application.team: honeybadger
version: '4.1.1'
home: https://github.com/giantswarm/docs-indexer
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
